# Generated by Django 3.2 on 2022-05-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notesmodel_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmodel',
            name='image',
            field=models.ImageField(blank=True, default='notes_images/default/default_notes.jpg', null=True, upload_to='notes_images/'),
        ),
    ]
